# api-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: api
  labels: { app: fastapi }
spec:
  type: ClusterIP
  selector: { app: fastapi }
  ports:
    - name: http
      port: 8000
      targetPort: 8000
