apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: <ECR or Docker Hub>/checklist_backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql+psycopg://app:app@postgres:5432/checkin"
            - name: JWT_SECRET
              value: "change_me"
            - name: CORS_ORIGINS
              value: "http://13.125.168.233,https://<도메인>"
